sudo: required
services:
    - docker

before_install:
    - docker build -t inyong0418/docker-react -f Dockerfile.dev .


script:
    - docker run inyong0418/docker-react npm run test -- --coverage

    